name: Run Selenium Tests

on:
  push:
    branches: [ main ]  # Se ejecuta al hacer push a la rama main
  pull_request:
    branches: [ main ]  # También en PRs hacia main

jobs:
  test:
    runs-on: ubuntu-latest  # Usa un entorno Linux (más fácil para configurar Chrome)

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Usa la versión que necesites

      # 3. Instala dependencias (Selenium)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      # 4. Instala Chrome y ChromeDriver (¿Necesario?)
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable  # Instala Chrome
          CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
          echo "Chrome version: $CHROME_VERSION"
          # Descarga ChromeDriver compatible
          wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION -O chromedriver-version.txt
          CHROMEDRIVER_VERSION=$(cat chromedriver-version.txt)
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      # 5. Ejecuta el test de Selenium
      - name: Run Selenium Test
        run: |
          python test_busqueda.py

      # (Opcional) Guarda reportes como artefactos
      - name: Upload test results
        if: always()  # Sube artefactos aunque falle
        uses: actions/upload-artifact@v3
        with:
          name: selenium-results
          path: |
            logs.txt