on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      # 1. Instala Chrome y obtiene la versión ANTES del caché
      - name: Install Chrome and set CHROME_VERSION
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
          echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV

      # 2. Cachea el chromedriver según la versión de Chrome
      - name: Cache ChromeDriver
        uses: actions/cache@v3
        id: cache-chromedriver
        with:
          path: chromedriver_linux64
          key: ${{ runner.os }}-chromedriver-${{ env.CHROME_VERSION }}

      # 3. Descarga ChromeDriver si no está cacheado (Chrome for Testing)
      - name: Download ChromeDriver if not cached
        if: steps.cache-chromedriver.outputs.cache-hit != 'true'
        run: |
          # Obtén la versión completa de Chrome instalada
          CHROME_VERSION_FULL=$(google-chrome --version | awk '{print $3}')
          echo "Chrome full version: $CHROME_VERSION_FULL"
          # Descarga el ChromeDriver correspondiente desde Chrome for Testing
          wget https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION_FULL}/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip -d chromedriver_linux64

      # 4. Mueve el binario a /usr/local/bin
      - name: Move ChromeDriver to PATH
        run: |
          sudo mv chromedriver_linux64/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Selenium Test #5. Ejecuta el test de Selenium
        run: python test_busqueda.py

      - name: Upload test results #6. Sube los resultados del test
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-results
          path: logs.txt